name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarQube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONARQ}}
          SONAR_HOST_URL: ${{ secrets.SONARURL }}
